# fly.toml app configuration file generated for aiostreams-bitter-resonance-2349 on 2025-05-01T16:21:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aiostreams-bitter-resonance-2349'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
